INSERT INTO commissions( id_representative_type, name,slug) VALUES ('1','Mesa de Decanos','mesa-de-decanos'),
('1','Mesa Directiva','mesa-directiva'),
('1','Junta de Coordinación Política','junta-de-coordinacion-politica'),
('1','Conferencia para la Dirección y Programación de los Trabajos Legislativos','conferencia-para-la-direccion-y-programacion-de-los-trabajos-legislativos'),
('1','Administración','administracion'),
('1','Trabajo y Previsión Social','trabajo-y-prevision-social'),
('1','Agricultura y Sistemas de Riego','agricultura-y-sistemas-de-riego'),
('1','Agua potable y Saneamiento','agua-potable-y-saneamiento'),
('1','Asuntos Frontera Norte','asuntos-frontera-norte'),
('1','Asuntos Frontera Sur-Sureste','asuntos-frontera-sur-sureste'),
('1','Asuntos Indígenas','asuntos-indigenas'),
('1','Asuntos Migratorios','asuntos-migratorios'),
('1','Atención a Grupos Vulnerables','atencion-a-grupos-vulnerables'),
('1','Cambio Climático','cambio-climatico'),
('1','Ciencia y Tecnología','ciencia-y-tecnologia'),
('1','Competitividad','competitividad'),
('1','Comunicaciones','comunicaciones'),
('1','Cultura y Cinematografía','cultura-y-cinematografia'),
('1','Defensa Nacional','defensa-nacional'),
('1','Deporte','deporte'),
('1','Derechos de la Niñez','derechos-de-la-ninez'),
('1','Derechos Humanos','derechos-humanos'),
('1','Desarrollo Metropolitano','desarrollo-metropolitano'),
('1','Desarrollo Rural','desarrollo-rural'),
('1','Desarrollo Social','desarrollo-social'),
('1','Economía','economia'),
('1','Educación Pública y Servicios Educativos','educacion-publica-y-servicios-educativos'),
('1','Energía','energia'),
('1','Igualdad de Género','igualdad-de-genero'),
('1','Fomento Cooperativo y Economía Social','fomento-cooperativo-y-economia-social'),
('1','Fortalecimiento al Federalismo','fortalecimiento-al-federalismo'),
('1','Transparencia y Anticorrupción','transparencia-y-anticorrupcion'),
('1','Ganadería','ganaderia'),
('1','Gobernación','gobernacion'),
('1','Hacienda y Crédito Público','hacienda-y-credito-publico'),
('1','Infraestructura','infraestructura'),
('1','Justicia','justicia'),
('1','Juventud','juventud'),
('1','Marina','marina'),
('1','Medio Ambiente y Recursos Naturales','medio-ambiente-y-recursos-naturales'),
('1','Desarrollo Urbano y Ordenamiento Territorial','desarrollo-urbano-y-ordenamiento-territorial'),
('1','Pesca','pesca'),
('1','Población','poblacion'),
('1','Presupuesto y Cuenta Pública','presupuesto-y-cuenta-publica'),
('1','Protección Civil','proteccion-civil'),
('1','Puntos Constitucionales','puntos-constitucionales'),
('1','Radio y Televisión','radio-y-television'),
('1','Recursos Hidráulicos','recursos-hidraulicos'),
('1','Reforma Agraria','reforma-agraria'),
('1','Relaciones Exteriores','relaciones-exteriores'),
('1','Salud','salud'),
('1','Seguridad Pública','seguridad-publica'),
('1','Seguridad Social','seguridad-social'),
('1','Transportes','transportes'),
('1','Turismo','turismo'),
('1','Vivienda','vivienda'),
('1','null','null'),
('1','Desarrollo Municipal','desarrollo-municipal'),
('1','Distrito Federal','distrito-federal'),
('1','Jurisdiccional','jurisdiccional'),
('1','Régimen Reglamentos y Prácticas Parlamentarias','regimen-reglamentos-y-practicas-parlamentarias'),
('1','Vigilancia de la Auditoría Superior de la Federación','vigilancia-de-la-auditoria-superior-de-la-federacion'),
('1','Continuidad al Diálogo y la Concertación entre los alumnos de las Escuelas Normales Rurales de Michoacán y los Gobiernos Estatal y Federal','continuidad-al-dialogo-y-la-concertacion-entre-los-alumnos-de-las-escuelas-normales-rurales-de-michoacan-y-los-gobiernos-estatal-y-federal'),
('1','Revisión del Funcionamiento de la Comisión Nacional para la Protección y Defensa de los Usuarios de Servicios Financieros en términos de lo dispuesto en el artículo 93 de la CPEUM','revision-del-funcionamiento-de-la-comision-nacional-para-la-proteccion-y-defensa-de-los-usuarios-de-servicios-financieros-en-terminos-de-lo-dispuesto-en-el-articulo-93-de-la-cpeum'),
('1','Bicamaral del Canal de Televisión del Congreso de la Unión','bicamaral-del-canal-de-television-del-congreso-de-la-union'),
('1','Bicamaral del Sistema de Bibliotecas del Congreso de la Unión','bicamaral-del-sistema-de-bibliotecas-del-congreso-de-la-union'),
('1','Bicamaral de Seguridad Nacional','bicamaral-de-seguridad-nacional'),
('1','Parlamento Latinoamericano (PARLATINO)','parlamento-latinoamericano-(parlatino)'),
('1','Confederación Parlamentaria de las Américas (COPA)','confederacion-parlamentaria-de-las-americas-(copa)'),
('1','Parlamento Centroamericano (PARLACEN)','parlamento-centroamericano-(parlacen)'),
('1','Comisión Parlamentaria Mixta Estados Unidos Mexicanos/Unión Europea','comision-parlamentaria-mixta-estados-unidos-mexicanos/union-europea'),
('1','Parlamentarios por las Américas (ParlAméricas)','parlamentarios-por-las-americas-(parlamericas)'),
('1','Unión Interparlamentaria Mundial (UIP)','union-interparlamentaria-mundial-(uip)'),
('1','Foro Parlamentario Asia-Pacifico (APPF)','foro-parlamentario-asia-pacifico-(appf)'),
('1','Asamblea Parlamentaria del Consejo de Europa','asamblea-parlamentaria-del-consejo-de-europa'),
('1','Consejo Editorial','consejo-editorial'),
('1','null','null'),
('1','null','null'),
('1','null','null'),
('1','null','null'),
('1','Industria Automotriz y del Acero','industria-automotriz-y-del-acero'),
('1','Cuenca Lerma-Chapala Santiago','cuenca-lerma-chapala-santiago'),
('1','Puertos y Marina Mercante','puertos-y-marina-mercante'),
('1','Industria Manufacturera y Maquiladora de Exportación','industria-manufacturera-y-maquiladora-de-exportacion'),
('1','Análisis de la Agroindustria Azucarera','analisis-de-la-agroindustria-azucarera'),
('1','Prevención Conservación y en su caso Restauración del Medio Ambiente en las Entidades Federativas donde se ubican las Instalaciones de PEMEX','prevencion-conservacion-y-en-su-caso-restauracion-del-medio-ambiente-en-las-entidades-federativas-donde-se-ubican-las-instalaciones-de-pemex'),
('1','Cuenca de Burgos','cuenca-de-burgos'),
('1','Conmemoración del Bicentenario del Congreso de Anáhuac y de los Sentimientos de la Nación','conmemoracion-del-bicentenario-del-congreso-de-anahuac-y-de-los-sentimientos-de-la-nacion'),
('1','Cuenca del Sistema Cutzamala','cuenca-del-sistema-cutzamala'),
('1','Participación Ciudadana','participacion-ciudadana'),
('1','Agenda Digital y Tecnologías de la Información','agenda-digital-y-tecnologias-de-la-informacion'),
('1','Energías Renovables','energias-renovables'),
('1','Lucha Contra la Trata de Personas','lucha-contra-la-trata-de-personas'),
('1','Seguimiento a la Regularización de los Solares Urbanos de las Zonas Metropolitanas del País','seguimiento-a-la-regularizacion-de-los-solares-urbanos-de-las-zonas-metropolitanas-del-pais'),
('1','Seguimiento al Cumplimiento de los Objetivos de Desarrollo del Milenio','seguimiento-al-cumplimiento-de-los-objetivos-de-desarrollo-del-milenio'),
('1','Minería','mineria'),
('1','Conocer y Dar Seguimiento Puntual y Exhaustivo a las Acciones que han Emprendido las Autoridades Competentes en relación a los Feminicidios registrados en México','conocer-y-dar-seguimiento-puntual-y-exhaustivo-a-las-acciones-que-han-emprendido-las-autoridades-competentes-en-relacion-a-los-feminicidios-registrados-en-mexico'),
('1','Ciudades Patrimonio de la Humanidad','ciudades-patrimonio-de-la-humanidad'),
('1','Impulsar la Agroindustria de la Palma de Coco y productos derivados','impulsar-la-agroindustria-de-la-palma-de-coco-y-productos-derivados'),
('1','Seguimiento a las Evaluaciones del Programa Especial Concurrente','seguimiento-a-las-evaluaciones-del-programa-especial-concurrente'),
('1','Seguimiento a las Prácticas Monopólicas y Regulación de Mercados','seguimiento-a-las-practicas-monopolicas-y-regulacion-de-mercados'),
('1','Asuntos Alimentarios','asuntos-alimentarios'),
('1','Tecnologías de la Información y Comunicación','tecnologias-de-la-informacion-y-comunicacion'),
('1','Del Café','del-cafe'),
('1','Programas Sociales','programas-sociales'),
('1','De la Alimentación','de-la-alimentacion'),
('1','Desarrollo Sustentable','desarrollo-sustentable'),
('1','Indagar el funcionamiento de las instancias del Gobierno Federal relacionadas con el otorgamiento de permisos para Juegos y Sorteos','indagar-el-funcionamiento-de-las-instancias-del-gobierno-federal-relacionadas-con-el-otorgamiento-de-permisos-para-juegos-y-sorteos'),
('1','Diálogo y la Conciliación para el Estado de Chiapas','dialogo-y-la-conciliacion-para-el-estado-de-chiapas'),
('1','Centro de Estudios de las Finanzas Públicas','centro-de-estudios-de-las-finanzas-publicas'),
('1','Centro de Estudios de Derecho e Investigaciones Parlamentarias','centro-de-estudios-de-derecho-e-investigaciones-parlamentarias'),
('1','Centro de Estudios Sociales y de Opinión Pública','centro-de-estudios-sociales-y-de-opinion-publica'),
('1','Centro de Estudios para el Desarrollo Rural Sustentable y la Soberanía Alimentaria','centro-de-estudios-para-el-desarrollo-rural-sustentable-y-la-soberania-alimentaria'),
('1','Centro de Estudios para el Adelanto de las Mujeres y la Equidad de Género','centro-de-estudios-para-el-adelanto-de-las-mujeres-y-la-equidad-de-genero'),
('1','Información Gestoría y Quejas','informacion-gestoria-y-quejas'),
('1','Fortalecimiento a la Educación Superior y la Capacitación para Impulsar el Desarrollo y la Competitividad','fortalecimiento-a-la-educacion-superior-y-la-capacitacion-para-impulsar-el-desarrollo-y-la-competitividad'),
('1','Cuenca del Bajo Pánuco','cuenca-del-bajo-panuco'),
('1','Promoción del Desarrollo Regional','promocion-del-desarrollo-regional'),
('1','null','null'),
('1','null','null'),
('1','null','null'),
('1','Evaluación de la Gestión y Operación del Centro de Desarrollo Infantil (CENDI) Antonia Nava de Catalán','evaluacion-de-la-gestion-y-operacion-del-centro-de-desarrollo-infantil-(cendi)-antonia-nava-de-catalan'),
('1','Alemania','alemania'),
('1','Angola','angola'),
('1','Arabia Saudita','arabia-saudita'),
('1','Argelia','argelia'),
('1','Argentina','argentina'),
('1','Australia','australia'),
('1','Austria','austria'),
('1','Azerbaiyán','azerbaiyan'),
('1','Bélgica','belgica'),
('1','Belice','belice'),
('1','Bielorrusia','bielorrusia'),
('1','Bolivia','bolivia'),
('1','Brasil','brasil'),
('1','Bulgaria','bulgaria'),
('1','Canadá','canada'),
('1','Chile','chile'),
('1','China','china'),
('1','Chipre','chipre'),
('1','Colombia','colombia'),
('1','Corea del Norte','corea-del-norte'),
('1','Corea del Sur','corea-del-sur'),
('1','Costa de Marfil','costa-de-marfil'),
('1','Costa Rica','costa-rica'),
('1','Croacia','croacia'),
('1','Cuba','cuba'),
('1','Dinamarca','dinamarca'),
('1','Ecuador','ecuador'),
('1','Egipto','egipto'),
('1','El Salvador','el-salvador'),
('1','Eslovaquia','eslovaquia'),
('1','España','espana'),
('1','Estados Unidos de América','estados-unidos-de-america'),
('1','Etiopia','etiopia'),
('1','Filipinas','filipinas'),
('1','Finlandia','finlandia'),
('1','Francia','francia'),
('1','Georgia','georgia'),
('1','Grecia','grecia'),
('1','Guatemala','guatemala'),
('1','Haití','haiti'),
('1','Holanda','holanda'),
('1','Honduras','honduras'),
('1','Hungría','hungria'),
('1','India','india'),
('1','Indonesia','indonesia'),
('1','Irak','irak'),
('1','Irán','iran'),
('1','Irlanda','irlanda'),
('1','Israel','israel'),
('1','Italia','italia'),
('1','Jamaica','jamaica'),
('1','Japón','japon'),
('1','Líbano','libano'),
('1','Libia','libia'),
('1','Lituania','lituania'),
('1','Malasia','malasia'),
('1','Marruecos','marruecos'),
('1','Mongolia','mongolia'),
('1','Montenegro','montenegro'),
('1','Nicaragua','nicaragua'),
('1','Noruega','noruega'),
('1','Nueva Zelanda','nueva-zelanda'),
('1','Pakistán','pakistan'),
('1','Palestina','palestina'),
('1','Panamá','panama'),
('1','Paraguay','paraguay'),
('1','Perú','peru'),
('1','Polonia','polonia'),
('1','Portugal','portugal'),
('1','Reino Unido','reino-unido'),
('1','República Árabe Saharaui','republica-arabe-saharaui'),
('1','República Checa','republica-checa'),
('1','Republica Dominicana','republica-dominicana'),
('1','Rumania','rumania'),
('1','Rusia','rusia'),
('1','Santa Lucia y Países del Caricom','santa-lucia-y-paises-del-caricom'),
('1','Serbia','serbia'),
('1','Singapur','singapur'),
('1','Sudáfrica','sudafrica'),
('1','Suecia','suecia'),
('1','Suiza','suiza'),
('1','Tailandia','tailandia'),
('1','Trinidad y Tobago','trinidad-y-tobago'),
('1','Turquía','turquia'),
('1','Ucrania','ucrania'),
('1','Uruguay','uruguay'),
('1','Venezuela','venezuela'),
('1','Vietnam','vietnam'),
('1','Organizador del Foro de Consulta sobre el Tema de la Política de Drogas','organizador-del-foro-de-consulta-sobre-el-tema-de-la-politica-de-drogas'),
('1','null','null'),
('1','null','null'),
('1','Nigeria','nigeria'),
('1','null','null'),
('1','Para Conmemorar el Centenario del Natalicio de Octavio Paz','para-conmemorar-el-centenario-del-natalicio-de-octavio-paz'),
('1','null','null'),
('1','null','null'),
('1','Seguimiento de los Programas Sociales Destinados a los Adultos Mayores','seguimiento-de-los-programas-sociales-destinados-a-los-adultos-mayores'),
('1','null','null'),
('1','Seguimiento a las investigaciones realizadas sobre el incendio de la Guarderia ABC de Hermosillo Sonora ocurrida el 5 de junio de 2009 así como de las causas que lo ocasionaron y la identificación de los probables responsables de la tragedia','seguimiento-a-las-investigaciones-realizadas-sobre-el-incendio-de-la-guarderia-abc-de-hermosillo-sonora-ocurrida-el-5-de-junio-de-2009-asi-como-de-las-causas-que-lo-ocasionaron-y-la-identificacion-de-los-probables-responsables-de-la-tragedia'),
('1','Seguimiento al ejercicio de los Recursos Federales que se Destinen o se Hayan Destinado a la Línea 12 del Metro','seguimiento-al-ejercicio-de-los-recursos-federales-que-se-destinen-o-se-hayan-destinado-a-la-linea-12-del-metro'),
('1','Contratos Celebrados por Petróleos Mexicanos sus Empresas Subsidiarias y Filiales de 2006 a la Fecha.','contratos-celebrados-por-petroleos-mexicanos-sus-empresas-subsidiarias-y-filiales-de-2006-a-la-fecha.'),
('1','Plural de Observación Electoral para dar Seguimiento al Proceso Electoral del Estado de Nayarit a celebrarse el próximo 6 de julio de 2014','plural-de-observacion-electoral-para-dar-seguimiento-al-proceso-electoral-del-estado-de-nayarit-a-celebrarse-el-proximo-6-de-julio-de-2014'),
('1','Seguimiento a la problemática generada por el derrame de diversas sustancias contaminantes en el río Sonora','seguimiento-a-la-problematica-generada-por-el-derrame-de-diversas-sustancias-contaminantes-en-el-rio-sonora'),
('1','XIV Reunión Interparlamentaria México-España por celebrarse en San Miguel de Allende Guanajuato los días 18 y 19 de septiembre de 2014','xiv-reunion-interparlamentaria-mexico-espana-por-celebrarse-en-san-miguel-de-allende-guanajuato-los-dias-18-y-19-de-septiembre-de-2014'),
('1','Seguimiento a las Investigaciones relacionadas con los hechos ocurridos en Iguala Guerrero a alumnos de la Escuela Normal Rural de Ayotzinapa Raúl Isidro Burgos.','Seguimiento-a-las-investigaciones-relacionadas-con-los-hechos-ocurridos-en-iguala-guerrero-a-alumnos-de-la-escuela-normal-rural-de-ayotzinapa-raul-isidro-burgos')
